spring.mail.host=mail.smtp2go.com
spring.mail.port=587
spring.mail.username=nwa_pfe
spring.mail.password=rtULJ02XBA2Xg0u8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
